version: 1
#build_arg_defaults:
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest'    
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt 
ansible_config: 'ansible.cfg'
additional_build_steps:
  prepend:
    #- RUN pip3 install --upgrade pip setuptools
    - RUN pip3 install --upgrade pip setuptools requests-oauthlib
  append:
    - RUN pip3 list installed

