version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest'    
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
ansible_config: 'ansible.cfg'